services:
  webhookfeeds:
    build:
      context: .
      args:
        - WEBHOOKFEEDS_ENV=development
    container_name: webhookfeeds
    volumes:
      - database:/usr/src/app/database
      - templates_custom:/usr/src/app/templates/custom
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  database:
  templates_custom:
