name: Test
on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'app/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. 100 chars as exception for the 88 from black
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
      - name: Test with pytest
        run: |
          pytest ./tests
